name: Deploy Content to Microsoft-Sentinel-Workspace [1dccefa1-a345-4a19-b5a2-d93bd14294a8]
# Note: This workflow will deploy everything in the root directory.
# To deploy content only from a specific path (for example SentinelContent):
#   1. Add the target path to the "paths" property like such
#    paths:
#    - 'SentinelContent/**'
#    - '!.github/workflows/**'
#    - '.github/workflows/sentinel-deploy-1dccefa1-a345-4a19-b5a2-d93bd14294a8.yml'
#   2. Append the path to the directory environment variable below
#       directory: '${{ github.workspace }}/SentinelContent'

on:
  push:
    branches: [ main ]
    paths:
    - '**'
    - '!.github/workflows/**'  # this filter prevents other workflow changes from triggering this workflow
    - '.github/workflows/sentinel-deploy-1dccefa1-a345-4a19-b5a2-d93bd14294a8.yml'

jobs:
  deploy-content:
    runs-on: windows-latest
    env:
      resourceGroupName: 'Microsoft-Sentinel-Resource-Group'
      workspaceName: 'Microsoft-Sentinel-Workspace'
      workspaceId: '11d389ee-474c-4e43-a44c-90f4be35cb85'
      directory: '${{ github.workspace }}'
      cloudEnv: 'AzureCloud'
      contentTypes: 'AnalyticsRule,HuntingQuery,CustomDetection'
      branch: 'main'
      sourceControlId: '1dccefa1-a345-4a19-b5a2-d93bd14294a8'
      rootDirectory: '${{ github.workspace }}'
      githubAuthToken: ${{ secrets.GITHUB_TOKEN }}
      smartDeployment: 'true'
    permissions:
      contents: write
      id-token: write # Require write permission to Fetch an OIDC token.

    steps:
    - name: Login to Azure (Attempt 1)
      continue-on-error: true
      id: login1
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_1dccefa1a3454a19b5a2d93bd14294a8 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_1dccefa1a3454a19b5a2d93bd14294a8 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_1dccefa1a3454a19b5a2d93bd14294a8 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 1 failed
      if: ${{ steps.login1.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 2)
      continue-on-error: true
      id: login2
      uses: azure/login@v2
      if: ${{ steps.login1.outcome=='failure' }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_1dccefa1a3454a19b5a2d93bd14294a8 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_1dccefa1a3454a19b5a2d93bd14294a8 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_1dccefa1a3454a19b5a2d93bd14294a8 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 2 failed
      if: ${{ steps.login2.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 3)
      continue-on-error: false
      id: login3
      uses: azure/login@v2
      if: ${{ steps.login2.outcome=='failure'  }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_1dccefa1a3454a19b5a2d93bd14294a8 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_1dccefa1a3454a19b5a2d93bd14294a8 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_1dccefa1a3454a19b5a2d93bd14294a8 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy Content to Microsoft Sentinel
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          ${{ github.workspace }}//.github/workflows/azure-sentinel-deploy-1dccefa1-a345-4a19-b5a2-d93bd14294a8.ps1